[package]
name = "badness-formatter"
version = "0.7.0"
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Deterministic, rule-based formatter for LaTeX and BibTeX"
license.workspace = true
repository.workspace = true
homepage = "https://badness.dev/"
documentation = "https://docs.rs/badness-formatter"
authors.workspace = true
include = ["/src/**/*", "/README.md", "/CHANGELOG.md"]
keywords = ["latex", "bibtex", "formatter"]
categories = ["development-tools", "text-processing"]

[dependencies]
badness-parser = { path = "../badness-parser", version = "0.6.0" }
rowan = "0.17.0"
schemars = { version = "1.2.1", optional = true }
serde = { version = "1.0.229", features = ["derive"], optional = true }

[dev-dependencies]
insta = "1.47.2"
serde_json = "1.0.151"
tempfile = "3.27.0"

[features]
default = []
serde = ["dep:serde"]
schema = ["serde", "dep:schemars"]
