[book]
title = "Badness"
authors = ["Johan Larsson"]
description = "Badness is a formatter, linter, and language server for LaTeX."
language = "en"

[output.html]
smart-punctuation = true
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/jolars/badness"
edit-url-template = "https://github.com/jolars/badness/edit/main/docs/{path}"

[preprocessor]

[preprocessor.doc-utils]
command = "cargo run --quiet --manifest-path doc-utils/Cargo.toml"
optional = true
