name = "badness-markdown"
main = "markdown-worker.mjs"
compatibility_date = "2026-10-05"
routes = [
  { pattern = "badness.dev/", zone_name = "badness.dev" },
  { pattern = "badness.dev/*.html", zone_name = "badness.dev" },
]
